### ISSUE TITLE
Build C library from skycoin/libskycoin

### ISSUE THREAD

**Issue by stdevHan** [simelo/libjava-skycoin#13]
## Expected Behavior

Since Skycoin 0.25.1 the C client library, SWIG, etc are developed in a separate repository (see skycoin/libskycoin#1) . LibSkycoin Java should use code in that repository .

## Actual Behavior

Submodule tracks `skycoin/skycoin@v0.25.0` .

## Specifications

  - Version: 0.25.0
  - Platform: GNU/Linux
  - Subsystem: all

## Possible Solution
Add `skycoin/libskycoin` as submodule and update GOPATH accordingly in `Makefile`, for instance ...

**Comment by stdevHan** [comment]
@stdevHan 👍

**Comment by stdevMac** [comment]
Solved in 802b4555ba2e667eb85a3afd1b9cfa838ae102bc
